connection:
  serial_port: /dev/ttyUSB0
  timeout: 2
  baudrate: 19200

events:
  poll_timeout: 0.2
  poll_address: 0x80

debug:
  level: DEBUG #    CRITICAL | ERROR | WARNING | INFO | DEBUG | NOTSET

security:
  key: 44

machine:
  pos_id: B374A402
  reg_key: 0000000000000000000000000000000000000000
  asset_number: 01000000
  denomination: 0.01
